/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Connector.ServerConnector;
import Controller.TPOperatorController;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Orders;
import observer.TPOperatorObserver;
import observerImpl.TPOperatorObserverImpl;

/**
 *
 * @author kushantha
 */
public class TelephoneOperator extends javax.swing.JFrame implements SuperTPOperator{
    private String operatorId;
    private TPOperatorObserver tPOperatorObserver;
    private String orderId;
   
    ;
    /**
     * Creates new form TelephoneOperator
     */
    public TelephoneOperator() throws NotBoundException, MalformedURLException, RemoteException{
        initComponents();
        this.operatorId = JOptionPane.showInputDialog(this, "Enter Telephone Operator Id :");
       
            TPOperatorController tPOperatorController = ServerConnector.getInstance().getTPOperatorController();
            this.tPOperatorObserver = new TPOperatorObserverImpl(this);
            tPOperatorController.addOperator(this.tPOperatorObserver);
            tPOperatorController.getOrderId(this.tPOperatorObserver);
            txtOrderID.setText(this.orderId);
            lblTp.setText(this.operatorId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @SuppressWarnings("unchecked")
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtCustName = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtOrderID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Order ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("TP NO :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        lblTp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTp.setText("1");
        jPanel1.add(lblTp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 110, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Customer Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Telephone No");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Qty");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        txtQty.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 230, 40));

        txtCustName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 230, 40));

        txtTelephoneNumber.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtTelephoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 230, 40));

        btnSend.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 90, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 590, 10));

        txtOrderID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
    
        try {
            TPOperatorController tPOperatorController = ServerConnector.getInstance().getTPOperatorController();
            tPOperatorController.placeOrder(new Orders(
                    txtOrderID.getText(),
                    this.operatorId,
                    txtCustName.getText(),
                    Integer.parseInt(txtTelephoneNumber.getText()),
                    Integer.parseInt(txtQty.getText()),
                    LocalDateTime.now().toString()
            ));
            tPOperatorController.getOrderId(this.tPOperatorObserver);
            JOptionPane.showMessageDialog(this, "Order Placed");
            txtOrderID.setText(this.orderId);
            txtCustName.setText("");
            txtTelephoneNumber.setText("");
            txtQty.setText("");
        } catch (NotBoundException ex) {
            Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnSendActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        try {
            TPOperatorController tPOperatorController = ServerConnector.getInstance().getTPOperatorController();
            tPOperatorController.removeOperator(tPOperatorObserver);
        } catch (NotBoundException ex) {
            Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelephoneOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelephoneOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelephoneOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelephoneOperator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
        
                try {
                    new TelephoneOperator().setVisible(true);
                } catch (NotBoundException ex) {
                    Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException ex) {
                    Logger.getLogger(TelephoneOperator.class.getName()).log(Level.SEVERE, null, ex);
                }
               

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblTp;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTelephoneNumber;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getOrderId(String string) {
         this.orderId = string;
        txtOrderID.setText(string);
    }
}
